name: Build & Deploy Backend

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: dotnet build -c Release
        working-directory: ManagerAPI.Backend
      - name: Publish
        run: dotnet publish -c Release
        working-directory: ManagerAPI.Backend
      - name: Clear
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASS }}
          script: rm -Rf /var/www/manager-backend/*
      - name: Copy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASS }}
          source: 'ManagerAPI.Backend/bin/Release/net5.0/publish/*'
          target: '/var/www/manager-backend/'
      - name: Fix copy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          passphrase: ${{ secrets.PASS }}
          script: mv /var/www/manager-backend/ManagerAPI.Backend /var/www/manager-backend/ManagerAPI && cp -R /var/www/manager-backend/ManagerAPI/bin/Release/net5.0/publish/* /var/www/manager-backend/ && rm -Rf /var/www/manager-backend/ManagerAPI
